apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: torchrun-demo
spec:
  nprocPerNode: "2"
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: pytorch-cpu:py3.8
              imagePullPolicy: Always
              command:
                - "torchrun"
                - "demo.py"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: pytorch-cpu:py3.8
              imagePullPolicy: Always
              command:
                - "torchrun"
                - "demo.py"
